name: Delete Old Workflows
on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "60"
        required: false
      runs_to_keep:
        description: "The amount of latest workflows runs to keep"
        default: "10"
        required: false

env:
  SCHEDULED_DAYS_OLD: "60"
  SCHEDULED_RUNS_TO_KEEP: "0"

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v4
        with:
          days_old: ${{ github.event.inputs.days_old || env.SCHEDULED_DAYS_OLD }} # optional
          runs_to_keep: ${{ github.event.inputs.runs_to_keep || env.SCHEDULED_RUNS_TO_KEEP }} # optional
